### PR TITLE
pgxtest: fix RunTestDataTypes for pgx

### PR DESCRIPTION
**Pull request by otan**
Timezone comparisons aren't a fair test because it truly depends on the person's machine running the program, so let's fix it up slightly by forcing comparisons against time.UTC.

### CODE REVIEW

**Comment by andy-kimball** [comment]
What do you mean that timezone comparisons aren't "a fair test"? What was the issue that led you to update this test? Timezones were one hard thing to get right with copyist, and found several bugs. I'd be concerned if we're no longer able to detect problems there.

**Review by andy-kimball — APPROVED** [review]
I see, OK. I looked closely at this, and the different drivers just have very different handling for timestamp values. I think normalizing to UTC is not really giving up much in terms of testing Copyist.

So I've got a few small comments, but otherwise, LGTM.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/copyist/21#-:-N6o4mm856NUr_dFFrGW:b-45li8l)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @andy-kimball and @otan)

___
*[`drivertest/commontest/common.go` line 270 at r1](https://reviewable.io/reviews/cockroachdb/copyist/21#-N6opthn3NIJGTd2-ltM:-N6opthn3NIJGTd2-ltN:b-16y1t4) ([raw file](https://github.com/cockroachdb/copyist/blob/d6a9180a6ada5579bd834205b1963070b6b522aa/drivertest/commontest/common.go#L270)):*
> ```Go
> 	require.Equal(t, DataTypes{
> 		Int: 1, Str: "foo\t\n ,]", TimeZ: parseTime("2000-01-01T10:00:00Z", driverName),
> 		Time: parseTime("2000-01-01T10:00:00+00:00", driverName), Bool: true,
> ```

Can you change this to use "2000-01-01T10:00:00Z" rather than "2000-01-01T10:00:00+00:00", since we always want UTC time. Same goes for below, i.e. "2000-02-02T11:11:11+00:00" => "2000-02-02T11:11:11Z".
___
*[`drivertest/commontest/common.go` line 380 at r1](https://reviewable.io/reviews/cockroachdb/copyist/21#-N6op_Wi4QCBKhXGBptZ:-N6op_Wi4QCBKhXGBpt_:brtozpo) ([raw file](https://github.com/cockroachdb/copyist/blob/d6a9180a6ada5579bd834205b1963070b6b522aa/drivertest/commontest/common.go#L380)):*
> ```Go
> }
> 
> func parseTime(s string, driverName string) time.Time {
> ```

Remove `driverName` from this function, since it's no longer used. Also, can you remove the `.UTC()` call here. That makes this function a bit more flexible, in case we need it to return non UTC times in the future. Instead, the caller can pass "Z" if it wants UTC times, as noted above.

**Comment by otan** [comment]
*[`drivertest/commontest/common.go` line 270 at r1](https://reviewable.io/reviews/cockroachdb/copyist/21#-N6opthn3NIJGTd2-ltM:-N6os87D2eDZiFpTRcGs:b-258per) ([raw file](https://github.com/cockroachdb/copyist/blob/d6a9180a6ada5579bd834205b1963070b6b522aa/drivertest/commontest/common.go#L270)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Can you change this to use "2000-01-01T10:00:00Z" rather than "2000-01-01T10:00:00+00:00", since we always want UTC time. Same goes for below, i.e. "2000-02-02T11:11:11+00:00" => "2000-02-02T11:11:11Z".
</blockquote></details>

`pq` doesn't like `Z`:

```
--- FAIL: TestDataTypes (0.34s)
    common.go:266:
        	Error Trace:	common.go:266
        	            				pgxtest_test.go:56
        	Error:      	Not equal:
        	            	expected: commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}
        	            	actual  : commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 21, 0, 0, 0, time.Local), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}
```

**Comment by andy-kimball** [comment]
*[`drivertest/commontest/common.go` line 270 at r1](https://reviewable.io/reviews/cockroachdb/copyist/21#-N6opthn3NIJGTd2-ltM:-N6p-ofvB2pLc33-SlJn:bhq03um) ([raw file](https://github.com/cockroachdb/copyist/blob/d6a9180a6ada5579bd834205b1963070b6b522aa/drivertest/commontest/common.go#L270)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

`pq` doesn't like `Z`:

```
--- FAIL: TestDataTypes (0.34s)
    common.go:266:
        	Error Trace:	common.go:266
        	            				pgxtest_test.go:56
        	Error:      	Not equal:
        	            	expected: commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}
        	            	actual  : commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 21, 0, 0, 0, time.Local), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}
```


</blockquote></details>

Did you remove `.UTC` from `parseTime` and also re-record? This seems to work fine on my machine.

**Comment by otan** [comment]
*[`drivertest/commontest/common.go` line 270 at r1](https://reviewable.io/reviews/cockroachdb/copyist/21#-N6opthn3NIJGTd2-ltM:-N6p2-Ad-4Uec7u7LP4W:bxe51rm) ([raw file](https://github.com/cockroachdb/copyist/blob/d6a9180a6ada5579bd834205b1963070b6b522aa/drivertest/commontest/common.go#L270)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Did you remove `.UTC` from `parseTime` and also re-record? This seems to work fine on my machine.
</blockquote></details>

yep. i'll push it, it fails on mine (D: !) with the above

**Comment by otan** [comment]
*[`drivertest/commontest/common.go` line 270 at r1](https://reviewable.io/reviews/cockroachdb/copyist/21#-N6opthn3NIJGTd2-ltM:-N6p2RKSBIl-1lAQCDqw:b-xl2djh) ([raw file](https://github.com/cockroachdb/copyist/blob/d6a9180a6ada5579bd834205b1963070b6b522aa/drivertest/commontest/common.go#L270)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

yep. i'll push it, it fails on mine (D: !) with the above
</blockquote></details>

sorry, full message:

```
--- FAIL: TestDataTypes (0.41s)
    common.go:266:
        	Error Trace:	common.go:266
        	            				pgxtest_test.go:56
        	Error:      	Not equal:
        	            	expected: commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}
        	            	actual  : commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 21, 0, 0, 0, time.Local), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -8,3 +8,11 @@
        	            	   ext: (int64) 63082317600,
        	            	-  loc: (*time.Location)(<nil>)
        	            	+  loc: (*time.Location)({
        	            	+   name: (string) "",
        	            	+   zone: ([]time.zone) <nil>,
        	            	+   tx: ([]time.zoneTrans) <nil>,
        	            	+   extend: (string) "",
        	            	+   cacheStart: (int64) 0,
        	            	+   cacheEnd: (int64) 0,
        	            	+   cacheZone: (*time.zone)(<nil>)
        	            	+  })
        	            	  },
        	Test:       	TestDataTypes
FAIL
FAIL	github.com/cockroachdb/copyist/drivertest/pgxtest	7.103s
--- FAIL: TestDataTypes (0.33s)
    common.go:266:
        	Error Trace:	common.go:266
        	            				pqtest_test.go:62
        	Error:      	Not equal:
        	            	expected: commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}
        	            	actual  : commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.Location("")), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -13,3 +13,28 @@
        	            	   ext: (int64) 63082317600,
        	            	-  loc: (*time.Location)(<nil>)
        	            	+  loc: (*time.Location)({
        	            	+   name: (string) "",
        	            	+   zone: ([]time.zone) (len=1) {
        	            	+    (time.zone) {
        	            	+     name: (string) "",
        	            	+     offset: (int) 0,
        	            	+     isDST: (bool) false
        	            	+    }
        	            	+   },
        	            	+   tx: ([]time.zoneTrans) (len=1) {
        	            	+    (time.zoneTrans) {
        	            	+     when: (int64) -9223372036854775808,
        	            	+     index: (uint8) 0,
        	            	+     isstd: (bool) false,
        	            	+     isutc: (bool) false
        	            	+    }
        	            	+   },
        	            	+   extend: (string) "",
        	            	+   cacheStart: (int64) -9223372036854775808,
        	            	+   cacheEnd: (int64) 9223372036854775807,
        	            	+   cacheZone: (*time.zone)({
        	            	+    name: (string) "",
        	            	+    offset: (int) 0,
        	            	+    isDST: (bool) false
        	            	+   })
        	            	+  })
        	            	  },
        	Test:       	TestDataTypes
FAIL
FAIL	github.com/cockroachdb/copyist/drivertest/pqtest	10.709s
```

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/copyist/21)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @andy-kimball and @otan)

___
*[`drivertest/commontest/common.go` line 270 at r1](https://reviewable.io/reviews/cockroachdb/copyist/21#-N6opthn3NIJGTd2-ltM:-N6p5l4l4DT0i4QTP6lk:b-2s9g1c) ([raw file](https://github.com/cockroachdb/copyist/blob/d6a9180a6ada5579bd834205b1963070b6b522aa/drivertest/commontest/common.go#L270)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

sorry, full message:

```
--- FAIL: TestDataTypes (0.41s)
    common.go:266:
        	Error Trace:	common.go:266
        	            				pgxtest_test.go:56
        	Error:      	Not equal:
        	            	expected: commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}
        	            	actual  : commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 21, 0, 0, 0, time.Local), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -8,3 +8,11 @@
        	            	   ext: (int64) 63082317600,
        	            	-  loc: (*time.Location)(<nil>)
        	            	+  loc: (*time.Location)({
        	            	+   name: (string) "",
        	            	+   zone: ([]time.zone) <nil>,
        	            	+   tx: ([]time.zoneTrans) <nil>,
        	            	+   extend: (string) "",
        	            	+   cacheStart: (int64) 0,
        	            	+   cacheEnd: (int64) 0,
        	            	+   cacheZone: (*time.zone)(<nil>)
        	            	+  })
        	            	  },
        	Test:       	TestDataTypes
FAIL
FAIL	github.com/cockroachdb/copyist/drivertest/pgxtest	7.103s
--- FAIL: TestDataTypes (0.33s)
    common.go:266:
        	Error Trace:	common.go:266
        	            				pqtest_test.go:62
        	Error:      	Not equal:
        	            	expected: commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}
        	            	actual  : commontest.DataTypes{Int:1, Str:"foo\t\n ,]", Dec:"100.1234", FltArr:"{1.1,1.2345678901234567}", TimeZ:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.UTC), Time:time.Date(2000, time.January, 1, 10, 0, 0, 0, time.Location("")), Bool:true, Bytes:[]uint8{0x41, 0x42, 0x43, 0x44}, Flt:1.1, Uuid:[]uint8{0x38, 0x62, 0x37, 0x38, 0x39, 0x37, 0x38, 0x62, 0x2d, 0x37, 0x64, 0x38, 0x62, 0x2d, 0x34, 0x38, 0x39, 0x65, 0x2d, 0x38, 0x63, 0x61, 0x39, 0x2d, 0x61, 0x63, 0x34, 0x62, 0x64, 0x63, 0x34, 0x39, 0x35, 0x61, 0x38, 0x32}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -13,3 +13,28 @@
        	            	   ext: (int64) 63082317600,
        	            	-  loc: (*time.Location)(<nil>)
        	            	+  loc: (*time.Location)({
        	            	+   name: (string) "",
        	            	+   zone: ([]time.zone) (len=1) {
        	            	+    (time.zone) {
        	            	+     name: (string) "",
        	            	+     offset: (int) 0,
        	            	+     isDST: (bool) false
        	            	+    }
        	            	+   },
        	            	+   tx: ([]time.zoneTrans) (len=1) {
        	            	+    (time.zoneTrans) {
        	            	+     when: (int64) -9223372036854775808,
        	            	+     index: (uint8) 0,
        	            	+     isstd: (bool) false,
        	            	+     isutc: (bool) false
        	            	+    }
        	            	+   },
        	            	+   extend: (string) "",
        	            	+   cacheStart: (int64) -9223372036854775808,
        	            	+   cacheEnd: (int64) 9223372036854775807,
        	            	+   cacheZone: (*time.zone)({
        	            	+    name: (string) "",
        	            	+    offset: (int) 0,
        	            	+    isDST: (bool) false
        	            	+   })
        	            	+  })
        	            	  },
        	Test:       	TestDataTypes
FAIL
FAIL	github.com/cockroachdb/copyist/drivertest/pqtest	10.709s
```
</blockquote></details>

Oh, I didn't mean you should remove these lines:
```
out.TimeZ = out.TimeZ.UTC()
out.Time = out.Time.UTC()
```
Those you still need. I was just asking that you convert "+00:00" => "Z" in the strings.

**Comment by otan** [comment]
behold! now this repo has CI!

**Pull request merged**
