### PR TITLE
call testing.T.Fatalf on recording mismatch instead of panicing

### PR DESCRIPTION
**Pull request by petermattis**
Call `testing.T.Fatalf` instead of panicing on various session errors
such as a recording mismatch. This provides a better user experience
when multiple tests have recording mismatches. Now each test will be
reported as failed, while previously only the first test would fail and
subsequent tests would not be run.

### CODE REVIEW

**Comment by andy-kimball** [comment]
I don't think `Fatalf` can be run on background goroutines, correct? That was the reason I originally used panic.

**Comment by petermattis** [comment]
Hrmm. Well, you can call `Fatalf` on a background goroutine, but it simply calls `runtime.Goexit` on that goroutine which might just cause the test to hang. Are we commonly calling into copyist from background goroutines? My experience is that we're almost always doing the work on the testing goroutine, though with jobs this might not be the case. We could call `testing.T.Fail` or `testing.T.Errorf` and then subsequently panic and allow the panic to be caught if there is an appropriate defer in the test which we could put in place in the copyist closer. Then if the panic happens on the testing goroutine we'll run subsequent tests, and if it happens on a background goroutine the test process will exit. Does that sound workable?

**Comment by andy-kimball** [comment]
I wouldn't say we "commonly" call copyist on a background goroutine, but yes, we do it sometimes.

As an alternative, what if we panicked if the goroutine that called `copyist.Open` is different than the one where the failure occurs? Otherwise, we'd call `Fatalf`. We already walk the stack looking for the test file, so we already assume that `copyist.Open` happens on the original foreground goroutine, so I don't think this would be much of a restriction.

**Comment by petermattis** [comment]
> As an alternative, what if we panicked if the goroutine that called copyist.Open is different than the one where the failure occurs? Otherwise, we'd call Fatalf. We already walk the stack looking for the test file, so we already assume that copyist.Open happens on the original foreground goroutine, so I don't think this would be much of a restriction.

I think my suggestion would give equivalent behavior to this, but wouldn't require introspecting the goroutine ID. Let me code up my suggestion to give you something more concrete to pick apart.

**Review by andy-kimball — APPROVED** [review]
:lgtm: with a couple small issues.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/copyist/15#-:-Mktmuwq-H9TexhExneb:b-7trs0r)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @andy-kimball and @petermattis)

___
*[copyist.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/copyist/15#-MksruaN0lxyqot3KNk-:-MksruaN0lxyqot3KNk0:bg86b4n) ([raw file](https://github.com/cockroachdb/copyist/blob/84a054e6e6c6333cf2cd63cac78f8123a981ae8a/copyist.go#L31)):*
> ```Go
> )
> 
> type testingT interface {
> ```

NIT: I'd add a comment here to make it clear that this is the subset of `testing.T` methods that are used by copyist.
___
*[session.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/copyist/15#-Mktl1Z62KYNKavDShql:-Mktl1Z62KYNKavDShqm:b-o7is61) ([raw file](https://github.com/cockroachdb/copyist/blob/84a054e6e6c6333cf2cd63cac78f8123a981ae8a/session.go#L169)):*
> ```Go
> type sessionError struct {
> 	error
> }
> ```

There are some weird extra characters at the end of the file.

**Review by petermattis — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/copyist/15#-:-MlFMF-I4sHd5pkGby-E:b-814g8k)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @andy-kimball)

___
*[copyist.go, line 31 at r2](https://reviewable.io/reviews/cockroachdb/copyist/15#-MksruaN0lxyqot3KNk-:-MlFLf7HDmUWcKBpLMRC:b-896fix) ([raw file](https://github.com/cockroachdb/copyist/blob/84a054e6e6c6333cf2cd63cac78f8123a981ae8a/copyist.go#L31)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

NIT: I'd add a comment here to make it clear that this is the subset of `testing.T` methods that are used by copyist.
</blockquote></details>

Done.
___
*[session.go, line 169 at r2](https://reviewable.io/reviews/cockroachdb/copyist/15#-Mktl1Z62KYNKavDShql:-MlFM8cg3h0DpvTudOX4:b-cbjc7e) ([raw file](https://github.com/cockroachdb/copyist/blob/84a054e6e6c6333cf2cd63cac78f8123a981ae8a/session.go#L169)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

There are some weird extra characters at the end of the file.
</blockquote></details>

I'm not seeing anything, though I did add a missing newline to the end of the file.

**Pull request merged**
