### PR TITLE
fix: implement driver.NamedValueChecker and if appropriate, forward to the underlying driver.Conn

### PR DESCRIPTION
**Pull request by dan-j**
See #26

### CODE REVIEW

**Comment by dan-j** [comment]
Hey! Any uptake on this?

**Comment by dan-j** [comment]
Hey @JeffSwenson, saw you as a reviewer on another PR, any chance you could take a look at this?

**Comment by dan-j** [comment]
Hey @chrisseto @otan @andy-kimball... sorry for the spam @'s, but is anyone maintaining this package anymore?

**Comment by otan** [comment]
do not have write access as I no longer work at the company :)

**Comment by chrisseto** [comment]
Same here :)

**Comment by JeffSwenson** [comment]
Thanks for the PR!

FYI we don't use copyist internally anymore. At a certain point managing all of the copyist records caused too many spurious merge conflicts and interacted poorly with our merge queue. We've switched to testing with https://github.com/cockroachdb/cockroach-go. The general strategy is we have a a backup that contains schema+fixtures. We create an ephemeral cockroach instance for the test run, restore it from the backup. Each unit test runs in its own transaction and the transaction rolls back when test finishes.

**Comment by dan-j** [comment]
Thanks @JeffSwenson! 

That's very interesting! I wasn't aware of cockroach-go, might have to take a look into that ourselves. In the meantime this library is a god-send compared to implement sql mocking 😅.

Is there any chance you can do a new v1.6.1 release? We had one project pinned to my PR, but another project started using 1.6.0 by default, ran into this issue, and they lost time investigating it before realising it was copyist and that this PR existed. Without a new release `go get` will just continue to get v1.6.0.

Has there been any thought on handing over maintenance to others outside of cockroach? It's been abandoned quite a while and there's a few dependencies out of date plus another PR looking for merging.

**Comment by JeffSwenson** [comment]
I merged the other pending PR and created a v1.7.0 tag for the release.

**Comment by JeffSwenson** [comment]
@andy-kimball and I chatted a bit about the future of this repo. If there is an active fork of the repo we would be willing to update the readme to direct folks to the fork. We are also considering open sourcing the rollback driver we use and we would direct folks to the use the rollback driver instead of copyist.

**Pull request merged**
